# LINKING

Pipeline: Spanish NER entities → Translation → Multilingual Embeddings → FAISS → SNOMED CT Linking

In [ ]:
!pip install -q transformers accelerate torch faiss-cpu numpy pandas tqdm

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.8/23.8 MB 41.9 MB/s eta 0:00:00

In [ ]:
import re
import torch
import torch.nn.functional as F
import numpy as np
import pandas as pd
import faiss
from tqdm import tqdm
from transformers import (
    MarianMTModel,
    MarianTokenizer,
    AutoTokenizer,
    AutoModel
)

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

Device: cuda

In [ ]:
# Upload the file of medical entities in Spanish
path_train = "/content/distemist_subtrack2_training1_linking.tsv"
df_ner = pd.read_csv(path_train, sep="\t", dtype={"code": str})

print(f"Entities to link: {len(df_ner)}")
display(df_ner.head())

Entities to link: 1512

,filename,mark,label,off0,off1,span,code,semantic_rel
0,es-S1139-76322014000100010-1,T1,ENFERMEDAD,2008,2047,apéndice cecal con signos inflamatorios,74400008,EXACT
1,es-S1139-76322014000100010-1,T2,ENFERMEDAD,1259,1277,cuadro obstructivo,81060008,EXACT
2,es-S1139-76322014000100010-1,T3,ENFERMEDAD,574,587,abdomen agudo,9209005,EXACT
3,es-S1139-76322014000100010-1,T4,ENFERMEDAD,753,770,apendicitis aguda,85189001,EXACT
4,es-S1130-05582017000200099-1,T1,ENFERMEDAD,50,58,fumadora,77176002,EXACT

In [ ]:
# Upload the SNOMED-CT knowledge base file
path_snomed = "/content/sct2_Description_Snapshot-en_INT_20260101.txt"

df_snapshot = pd.read_csv(
    path_snomed,
    sep="\t",
    usecols=["conceptId", "term", "active", "typeId"],
    dtype={"conceptId": str},
)

#Keep only active FSN
df_snapshot["semantic_tag"] = df_snapshot["term"].str.extract(r"\(([^)]+)\)$")
df_snapshot = df_snapshot.dropna(subset= ["semantic_tag"])

def clean_fsn(term: str) -> str:
  """Remove trailing semantic tag from FSN, e.g. 'Fracture (disorder)' → 'Fracture'."""
  return re.sub(r"\s*\([^)]+\)$", "", str(term)).strip()

df_snapshot["term_clean"] = df_snapshot["term"].apply(clean_fsn)
df_snapshot = df_snapshot.drop_duplicates(subset=["conceptId"]).reset_index(drop=True)

#Guarantee all target conceptId are included
target_codes = set(df_ner["code"].dropna().unique())
df_targets = df_snapshot[df_snapshot["conceptId"].isin(target_codes)].copy()
df_non_targets = df_snapshot[~df_snapshot["conceptId"].isin(target_codes)].copy()

# Stratified sample of non-target concepts (distractors)
N_PER_TAG = 3000
df_background = (
    df_non_targets
    .groupby("semantic_tag", group_keys=False)
    .apply(lambda x: x.sample(n = min(len(x), N_PER_TAG), random_state = 42))
    .reset_index(drop=True)
)

df_snomed = pd.concat([df_targets, df_background], ignore_index=True).drop_duplicates(subset= ["conceptId"])

print(f"Full SNOMED snapshot: {len(df_snapshot):,} active FSN concepts")
print(f"Target concepts guaranteed in index: {len(df_targets):,}")
print(f"Background distractor concepts: {len(df_background):,}")
print(f"Final SNOMED index size: {len(df_snomed):,} concepts")
print(f"Semantic tags preserved: {df_snomed['semantic_tag'].nunique()}")

Full SNOMED snapshot: 528,897 active FSN concepts
Target concepts guaranteed in index: 866
Background distractor concepts: 78,389
Final SNOMED index size: 79,255 concepts
Semantic tags preserved: 4335

/tmp/ipython-input-457773554.py:31: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.sample(n = min(len(x), N_PER_TAG), random_state = 42))

In [ ]:
# Dictionary of medical terminology with its respective english translation (* Verify with a specialist )
MEDICAL_DICT = {
    "fractura conminuta": "comminuted fracture",
    "infarto agudo de miocardio": "acute myocardial infarction",
    "luxación glenohumeral": "glenohumeral dislocation",
    "lesiones cutáneas": "skin lesion",
    "diabetes": "diabetes mellitus",
    "tumor de células granulares": "granular cell tumor",
    "insuficiencia renal aguda": "acute renal insufficiency",
    "leucemia mieloide crónica": "chronic myeloid leukemia",
    "hta": "hypertensive disorder",          # abbreviation
    "dm tipo ii": "diabetes mellitus type 2", # abbreviation
    "dm tipo 2": "diabetes mellitus type 2",
    "edentulismo parcial de ambas arcadas": "partial edentulism of both arches",
    "glaucoma primario de ángulo abierto": "primary open-angle glaucoma",
    "esofagitis péptica": "peptic esophagitis",
    "gastroenteritis aguda": "acute gastroenteritis",
    "accidente isquémico transitorio cerebral": "transient ischemic attack",
    "tumor miofibroblástico inflamatorio vesical": "inflammatory myofibroblastic tumor of bladder",
    "espondiloartrosis grave": "severe spondyloarthrosis",
    "crisis focales de origen temporal derecho": "focal seizures of right temporal lobe origin",
    "descargas epileptiformes temporales": "temporal epileptiform discharges",
    "contractura capsular": "capsular contracture",
    "dehiscencia de herida en ambas mamas": "wound dehiscence of both breasts",
    "trombosis segmentaria de la vena dorsal superficial del pene": "segmental thrombosis of superficial dorsal vein of penis",
    "quiste radicular residual": "residual radicular cyst",
    "proceso miopático inflamatorio": "inflammatory myopathic process",
    "riñón derecho displásico multiquístico": "multicystic dysplastic right kidney",
    "lagunas coriorretinianas": "chorioretinal lacunae",
    "anomalías de la migración neuronal": "neuronal migration anomalies",
    "diseminación metastásica": "metastatic dissemination",
    "cuadro catarral": "catarrhal syndrome",
    "obstrucción nasal": "nasal obstruction",
    "metabolitos de cocaína en orina": "cocaine metabolites in urine",
    "polineuropatía": "polyneuropathy",
    "problemas de coagulación": "coagulation problem",
}

def apply_dictionary(texts: list[str], dictionary: dict) -> list[str | None]:
  """
  Return the dictionary translation for known terms, or None for unknown terms
  """
  return [dictionary.get(t.strip().lower(), None) for t in texts]

dict_results = apply_dictionary(df_ner["span"].tolist(), MEDICAL_DICT)
needs_neural = [r is None for r in dict_results]

print(f"Covered by dictionary : {sum(r is not None for r in dict_results)}")
print(f"Needs neural translation: {sum(needs_neural)}")

Covered by dictionary : 47
Needs neural translation: 1465

In [ ]:
#Translates what the dict din't cover

def postprocess_medical(text: str) -> str:
  """Applies specific medical terminology corrections to a given text """
  corrections = {
      r"\bswelling\b": "edema",
      r"\bhigh blood pressure\b": "hypertension",
  }
  for pattern, replacement in corrections.items():
    text = re.sub(pattern, replacement, text, flags= re.IGNORECASE)
  return text

# Model to translate from spanish to english
print("Loading translation model ((Helsinki-NLP/opus-mt-es-en))")
trans_tokenizer = MarianTokenizer.from_pretrained("Helsinki-NLP/opus-mt-es-en")
trans_model = MarianMTModel.from_pretrained("Helsinki-NLP/opus-mt-es-en").to(device)
trans_model.eval()

def translate_batch(texts: list[str], batch_size: int = 64) -> list[str]:
  """Translate a list of Spanish strings to English in batches"""
  translated = []
  for i in tqdm(range(0, len(texts), batch_size), desc = "Translating"):
    batch = texts[i : i + batch_size]
    inputs = trans_tokenizer(
        batch,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=512,
    ).to(device)
    with torch.no_grad():
      generated = trans_model.generate(**inputs, num_beams=4)
    decoded = trans_tokenizer.batch_decode(generated, skip_special_tokens = True)
    translated.extend(postprocess_medical(d) for d in decoded)
  return translated

#Translate entities not covered by dictionary
texts_for_neural = [
    df_ner["span"].iloc[i] for i, needs in enumerate(needs_neural) if needs
]
neural_results = translate_batch(texts_for_neural)

#Merge dictionary hits + neural translations
neural_iter = iter(neural_results)
final_translations = [
    next(neural_iter) if needs else dict_hit
    for needs, dict_hit in zip(needs_neural, dict_results)
]
df_ner["span_en"] = final_translations

print(f"\nTranslation complete. Example:")
print(f"  ES: {df_ner['span'].iloc[0]}")
print(f"  EN: {df_ner['span_en'].iloc[0]}")

#Comparing
df_ner["translation_changed"] = (
df_ner["span"].str.strip().str.lower()!= df_ner["span_en"].str.strip().str.lower()
)

unchanged = df_ner[~df_ner["translation_changed"]]
print(f"Entities where translation appears unchanged: {len(unchanged)}")
if len(unchanged):
  display(unchanged[["span","span_en"]].head(10))

#Show translation table
display(df_ner[["span","span_en", "translation_changed"]].head(30))

Loading translation model ((Helsinki-NLP/opus-mt-es-en))

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/44.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/826k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/802k [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:176: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")

config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/312M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/312M [00:00<?, ?B/s]

The tied weights mapping and config for this model specifies to tie model.shared.weight to model.decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

Translating: 100%|██████████| 23/23 [00:18<00:00,  1.27it/s]

Translation complete. Example:
  ES: apéndice cecal con signos inflamatorios
  EN: cecal appendix with inflammatory signs
Entities where translation appears unchanged: 134

                  span            span_en
9               dengue             dengue
89           madarosis          madarosis
109       pancreatitis       pancreatitis
118                HCL                HCL
121                HCL                HCL
175             lipoma             lipoma
222  neurofibromatosis  neurofibromatosis
224               NVSR               NVSR
225               NVSR               NVSR
226       tuberculosis       tuberculosis

,span,span_en,translation_changed
0,apéndice cecal con signos inflamatorios,cecal appendix with inflammatory signs,True
1,cuadro obstructivo,obstructive table,True
2,abdomen agudo,acute abdomen,True
3,apendicitis aguda,acute appendicitis,True
4,fumadora,smoker,True
5,alergias medicamentosas,medicated allergies,True
6,fascitis nodular,nodular fasciitis,True
7,lesión,injury,True
8,lesión,injury,True
9,dengue,dengue,False
10,fumadora ocasional,occasional smoker,True
11,dengue hemorrágico grado 1 inducido por el AAS,grade 1 hemorrhagic dengue induced by ASA,True
12,"exantema hemorrágico, simétrico, máculo-papula...","haemorrhagic, symmetric, maculo-papular rash i...",True
13,picaduras de mosquitos,mosquito bites,True
14,adenopatías latero y retrocervicales así como ...,latero and retrocervical as well as preatrial ...,True
15,hepatoesplenomegalia,Hepatosplenomegaly,True
16,petequias en la fosa antecubital derecha,petechiae in the right antecubital fossa,True
17,ictus isquémico,ischemic stroke,True
18,tromboembolismo venoso profundo,Deep venous thromboembolism,True
19,obesidad extrema,extreme obesity,True
20,distorsiones cognitivas,cognitive distortions,True
21,trastorno límite de personalidad,personality limit disorder,True
22,retraso mental,mental retardation,True
23,conductas sexuales desviadas,deviant sexual behaviour,True
24,distorsiones cognitivas,cognitive distortions,True
25,conductas metasimulativas,metasimulative behaviours,True
26,luxación de hombro,shoulder dislocation,True
27,lesiones,injuries,True
28,lesiones,injuries,True
29,lesiones,injuries,True

In [ ]:
# Loading a pre-trained multilingual embedding model from Hugging Face.
print("Loading embedding model (intfloat/multilingual-e5-large)")
emb_model_name = "intfloat/multilingual-e5-large"
emb_tokenizer = AutoTokenizer.from_pretrained(emb_model_name)
emb_model = AutoModel.from_pretrained(emb_model_name).to(device)
emb_model.eval()

Loading embedding model (intfloat/multilingual-e5-large)

config.json:   0%|          | 0.00/690 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/418 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/280 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.24G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

XLMRobertaModel LOAD REPORT from: intfloat/multilingual-e5-large
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

XLMRobertaModel(
  (embeddings): XLMRobertaEmbeddings(
    (word_embeddings): Embedding(250002, 1024, padding_idx=1)
    (token_type_embeddings): Embedding(1, 1024)
    (LayerNorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
    (position_embeddings): Embedding(514, 1024, padding_idx=1)
  )
  (encoder): XLMRobertaEncoder(
    (layer): ModuleList(
      (0-23): 24 x XLMRobertaLayer(
        (attention): XLMRobertaAttention(
          (self): XLMRobertaSelfAttention(
            (query): Linear(in_features=1024, out_features=1024, bias=True)
            (key): Linear(in_features=1024, out_features=1024, bias=True)
            (value): Linear(in_features=1024, out_features=1024, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): XLMRobertaSelfOutput(
            (dense): Linear(in_features=1024, out_features=1024, bias=True)
            (LayerNorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): XLMRobertaIntermediate(
          (dense): Linear(in_features=1024, out_features=4096, bias=True)
          (intermediate_act_fn): GELUActivation()
        )
        (output): XLMRobertaOutput(
          (dense): Linear(in_features=4096, out_features=1024, bias=True)
          (LayerNorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
  )
  (pooler): XLMRobertaPooler(
    (dense): Linear(in_features=1024, out_features=1024, bias=True)
    (activation): Tanh()
  )
)

In [ ]:
def mean_pooling(model_output, attention_mask) -> torch.Tensor:
  """Compute mean-pooled sentence embedding from token embeddings"""
  token_emb = model_output.last_hidden_state
  mask_expanded = attention_mask.unsqueeze(-1).expand(token_emb.size()).float()
  return (token_emb * mask_expanded).sum(1) / mask_expanded.sum(1).clamp(min=1e-9)

def generate_embeddings(
    texts: list[str],     #list of strings to embed
    prefix: str,          #"query:" or "passage:"
    model,                #loaded AutoModel
    tokenizer,            #loaded Autokenizer
    batch_size: int = 32, #numbers of texts per gpu batch
) -> np.ndarray:          #returns np.ndarray
  """
  query for entities to search with
  passage: for knowledge-base entries (SNOMED terms)
  """

  all_embeddings = []
  prefixed = [f"{prefix}{text}" for text in texts]

  for i in tqdm(range(0, len(prefixed), batch_size), desc=f"Embedding [{prefix.strip()}]"):
    batch = prefixed[i : i + batch_size]
    encoded = tokenizer(
        batch,
        padding=True,
        truncation=True,
        max_length=512,
        return_tensors="pt"
    ).to(device)

    with torch.no_grad():
      output = model(**encoded)

    emb = mean_pooling(output, encoded["attention_mask"])
    emb = F.normalize(emb, p=2, dim=1)
    all_embeddings.append(emb.cpu().numpy()) # Changed .extend to .append

  return np.concatenate(all_embeddings, axis=0)

In [ ]:
#Generate embeddings for SNOMED knowled base
print("Generating SNOMED embeddings (passage prefix)...")
snomed_texts = df_snomed["term_clean"].tolist()
snomed_emb = generate_embeddings(
    snomed_texts,
    prefix= "passage:",
    model= emb_model,
    tokenizer=emb_tokenizer,
    batch_size=16
)
print(f"SNOMED embedding matrix: {snomed_emb.shape}")

Generating SNOMED embeddings (passage prefix)...

Embedding [passage:]: 100%|██████████| 4954/4954 [07:13<00:00, 11.42it/s]

SNOMED embedding matrix: (79255, 1024)

In [ ]:
#Generates embeddings for query entities
USE_TRANSLATION = True

query_texts = df_ner["span_en"].tolist() if USE_TRANSLATION else df_ner["span"].tolist()
lang_tag = "English (translated)" if USE_TRANSLATION else "Spanish (original)"

print(f"Generating query embeddings ({lang_tag})")
query_emb = generate_embeddings(
    query_texts,
    prefix= "query:",
    model= emb_model,
    tokenizer=emb_tokenizer,
    batch_size=16
)
print(f"Query embedding matrix: {query_emb.shape}"
)

Generating query embeddings (English (translated))

Embedding [query:]: 100%|██████████| 95/95 [00:07<00:00, 13.36it/s]

Query embedding matrix: (1512, 1024)

In [ ]:
""" Set up and use a FAISS index for similarity search """

d = snomed_emb.shape[1] # 1024 is the numbrer of features in each embedding
index = faiss.IndexFlatIP(d)  #Inner product

try:
  res = faiss.StandardGpuResources()
  index = faiss.index_cpu_to_gpu(res, 0,index)
  print("FASS running on GPU")
except Exception:
  print("FASS running on CPU")

# Adds all the pre-genereted SNOMED concpet embeddings for making searchable
index.add(snomed_emb)
print(f"Vectors indexed: {index.ntotal:,}")

K = 10      # Number of nearest neighbors
D_scores, I_indices = index.search(query_emb, K)
print(f"Search complete. Top {K} candidates retrieved for {len(query_emb)} queries")

FASS running on CPU
Vectors indexed: 79,255
Search complete. Top 10 candidates retrieved for 1512 queries

In [ ]:
#Evalute predictions
snomed_ids = df_snomed["conceptId"].tolist()
snomed_terms = df_snomed["term_clean"].tolist()

predictions = []
top1_correct = top5_correct = top10_correct = 0
total = len(df_ner)

for row_i, row in df_ner.iterrows():
    true_code      = row["code"]
    retrieved_idxs = I_indices[row_i]
    pred_codes     = [snomed_ids[idx] for idx in retrieved_idxs]

    if true_code in pred_codes[:1]:
        top1_correct += 1
    if true_code in pred_codes[:5]:
        top5_correct += 1
    if true_code in pred_codes[:10]:
        top10_correct += 1

    predictions.append({
        "span":        row["span"],
        "span_en":     row["span_en"],
        "true_code":   true_code,
        "pred_code":   pred_codes[0],
        "pred_term":   snomed_terms[retrieved_idxs[0]],
        "score":       D_scores[row_i][0],
        "match":       true_code == pred_codes[0],
        "in_top5":     true_code in pred_codes[:5],
        "in_top10":    true_code in pred_codes[:10],
    })

df_preds = pd.DataFrame(predictions)

print(f"  EVALUATION RESULTS  ({total} entities, {lang_tag})")
print(f"{'='*50}")
print(f"  Accuracy  (Top-1 Recall) : {top1_correct  / total:.4f}  ({top1_correct}/{total})")
print(f"  Recall@5                 : {top5_correct  / total:.4f}  ({top5_correct}/{total})")
print(f"  Recall@10                : {top10_correct / total:.4f}  ({top10_correct}/{total})")

  EVALUATION RESULTS  (1512 entities, English (translated))
==================================================
  Accuracy  (Top-1 Recall) : 0.4114  (622/1512)
  Recall@5                 : 0.6052  (915/1512)
  Recall@10                : 0.6601  (998/1512)

In [ ]:
print("\n Correct predictions (sample):")
display(
    df_preds[df_preds["match"]]
    [["span", "span_en", "true_code", "pred_term", "score"]]
    .head(10)
)

print("\n Incorrect predictions (sample):")
display(
    df_preds[~df_preds["match"]]
    [["span", "span_en", "true_code", "pred_code", "pred_term", "score"]]
    .head(10)
)

# Entities where the true code wasn't even in top-10 (hardest cases)
missed_top10 = df_preds[~df_preds["in_top10"]]
print(f"\n Entities not recovered in Top-10: {len(missed_top10)} ({len(missed_top10)/total:.1%})")
display(missed_top10[["span", "span_en", "true_code"]].head(10))

 Correct predictions (sample):

,span,span_en,true_code,pred_term,score
2,abdomen agudo,acute abdomen,9209005,Acute abdomen,0.931379
3,apendicitis aguda,acute appendicitis,85189001,Acute appendicitis,0.927677
5,alergias medicamentosas,medicated allergies,416098002,Drug allergy,0.873672
6,fascitis nodular,nodular fasciitis,400138001,Nodular fasciitis,0.912753
9,dengue,dengue,38362002,Dengue,0.892788
11,dengue hemorrágico grado 1 inducido por el AAS,grade 1 hemorrhagic dengue induced by ASA,409676000,"Dengue hemorrhagic fever, grade I",0.868001
13,picaduras de mosquitos,mosquito bites,283344005,Mosquito bite,0.904283
15,hepatoesplenomegalia,Hepatosplenomegaly,36760000,Hepatosplenomegaly,0.915144
17,ictus isquémico,ischemic stroke,422504002,Ischemic stroke,0.911888
18,tromboembolismo venoso profundo,Deep venous thromboembolism,128053003,Deep venous thrombosis,0.917161

 Incorrect predictions (sample):

,span,span_en,true_code,pred_code,pred_term,score
0,apéndice cecal con signos inflamatorios,cecal appendix with inflammatory signs,74400008,18526009,Disease of appendix,0.861336
1,cuadro obstructivo,obstructive table,81060008,708531006,Obstructive lesion,0.865967
4,fumadora,smoker,77176002,160622001,Smoker,0.898689
7,lesión,injury,417163006,246240008,Type of injury,0.912292
8,lesión,injury,417163006,246240008,Type of injury,0.912292
10,fumadora ocasional,occasional smoker,77176002,266920004,Occasional cigarette smoker,0.920628
12,"exantema hemorrágico, simétrico, máculo-papula...","haemorrhagic, symmetric, maculo-papular rash i...",271807003+128121009+128605003,89757007,Macular rash,0.864508
14,adenopatías latero y retrocervicales así como ...,latero and retrocervical as well as preatrial ...,127086001+127078001,76887001,"Anterior fascicular block, posterior fascicula...",0.858969
16,petequias en la fosa antecubital derecha,petechiae in the right antecubital fossa,423716004,244001006,Antecubital fossa,0.860769
22,retraso mental,mental retardation,110359009,61152003,Moderate mental retardation,0.889079

 Entities not recovered in Top-10: 514 (34.0%)

,span,span_en,true_code
1,cuadro obstructivo,obstructive table,81060008
7,lesión,injury,417163006
8,lesión,injury,417163006
10,fumadora ocasional,occasional smoker,77176002
12,"exantema hemorrágico, simétrico, máculo-papula...","haemorrhagic, symmetric, maculo-papular rash i...",271807003+128121009+128605003
14,adenopatías latero y retrocervicales así como ...,latero and retrocervical as well as preatrial ...,127086001+127078001
16,petequias en la fosa antecubital derecha,petechiae in the right antecubital fossa,423716004
22,retraso mental,mental retardation,110359009
23,conductas sexuales desviadas,deviant sexual behaviour,50299009
25,conductas metasimulativas,metasimulative behaviours,430909002

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!git clone https://@github.com/<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><Quarcks1>/<YOUR_REPO_NAME>.git